on:
  push:
    branches: [main]

name: conditions

jobs:
  run-r:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rvest

      - name: Run R script
        run: |
          source('min_forecast.R')
          rmd = min_forecast('rmd', 'stage')
          Sys.setenv(hrk = min_forecast('hrk', 'flow'))
        shell: Rscript {0}
        
      - name: test stage
        if: ${{ env.rmd < 5.5 }}
        run: echo "Yes!"
        
      - name: test flow
        if: ${{ env.hrk < 5 }}
        run: echo "Yes times two!"

# - name: CINotify Email
#   if: ${{ env.rmd < 5.5}}
#   uses: cinotify/github-action@v1.1.0

