on:
  push:
    branches: [main]

name: conditions

jobs:
  run-r:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rvest

      - name: Run R script
        run: |
          source('min_forecast.R')
          rmd = min_forecast('rmd', 'stage')
          hrk = min_forecast('hrk', 'flow')
        shell: Rscript {0}
        
      - name: CINotify Email RMD
        if: ${{ env.rmd < 5.5}} || ${{ env.hrk < 5}}
        uses: cinotify/github-action@v1.1.0
        with:
          to: 'mikeob9@gmail.com'
          subject: 'Get ready to go sampling!'
          body: |
            Richmond-Westham is forecast to be $rmd ft.
            Holcomb Rock is forecast to be $hrk kcfs.
            Erin, this is an automated email. Contact Mike to get rid of it.
        
