on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1-5'

name: conditions

jobs:
  run-r:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CRED_FILE: ${{ secrets.GMAIL_SECRET }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rvest
            any::tidyr
            any::ggplot2
            any::blastula
            any::gt

      - name: Run R script
        run: |
          source('scrape_and_notify.R')
        shell: Rscript {0}
        
