on:
  push:
    branches: [main]

name: conditions

jobs:
  run-r:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rvest

      - name: Run R script
        run: |
          source('min_forecast.R')
          rmd = min_forecast('rmd', 'stage')
          hrk = min_forecast('hrk', 'flow')
        shell: Rscript {0}
        
      - name: CINotify Email RMD
        if: ${{ env.rmd < 5.5}}
        uses: cinotify/github-action@v1.1.0
        to: 'mikeob9@gmail.com'
        subject: 'Get ready to go sampling at!'
        body: 'Richmond-Westham is forecast to be <5.5 ft.'
        
      # - name: CINotify Email HRK
      #   if: ${{ env.rmd < 5.5 }}
      #   uses: cinotify/github-action@v1.1.0
        
