on:
  push:
    branches: [main]

name: conditions

jobs:
  run-r:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
          any::rvest

      - name: R R script
        run: |
          Rscript "min_forecast.R"
          Rscript -e "rmd = min_forecast('rmd', 'stage')"
          Rscript -e "hrk = min_forecast('hrk', 'flow')"
        
      - name: test
        if: ${{ env.rmd < 5.5 }}
        run: echo "Yes!"

# - name: CINotify Email
#   if: ${{ env.rmd < 5.5}}
#   uses: cinotify/github-action@v1.1.0

